parameters:
- name: dependencies
  type: object
  default: []
- name: variableGroups
  type: object

stages:
- stage: build
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    - '${{ each variableGroup in parameters.variableGroups }}':
      - group: '${{variableGroup}}'
  jobs:
  - job: BuildApplication
    variables:
      NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-latest'
    workspace:
      clean: all
    steps:
      - template: ../jobs/tlevels-build-application-job.yml

  - job: BuildDACPAC
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-latest'
    steps:
      - template: ../jobs/tlevels-build-dacpac-job.yml

  - job: RunTests
    dependsOn: BuildApplication
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/heads/Release*'), eq(variables['Build.Reason'], 'PullRequest'))
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-latest'
    steps:
      - template: ../jobs/tlevels-run-tests-job.yml

##