parameters:
  - name: environmentTagName
    type: string
  - name: stageName
    type: string
  - name: dependencies
    type: object
  - name: environmentName
    type: string
  - name: environmentId
    type: string
  - name: sharedEnvironmentId
    type: string
  - name: serviceConnection
    type: string
  - name: applicationName
    type: string
stages:
  - stage: Deploy_${{parameters.environmentId}}
    dependsOn:
      - "${{ each dependency in parameters.dependencies }}":
          - "${{dependency}}"
    variables:
      - group: platform-global-${{parameters.applicationName}}
      - group: platform-${{parameters.environmentName}}
      - group: platform-${{parameters.environmentName}}-${{parameters.applicationName}}
      - name: BaseName
        value: "s126${{parameters.environmentId}}-${{parameters.applicationName}}-${{parameters.environmentName}}"
      - name: ResourceGroupName
        value: "$(BaseName)"
      - name: EnvironmentName
        value: ${{ parameters.environmentName }}
      - name: environmentTagName
        value: ${{parameters.environmentTagName}}

    displayName: "${{parameters.environmentName}} [${{parameters.environmentId}}] deployment"
    jobs:
      - template: ../jobs/tlevels-infrastructure-job.yml
        parameters:
          BaseName: $(BaseName)
          serviceConnection: ${{ parameters.serviceConnection }}
          sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
          environmentName: ${{ parameters.environmentName }}

      - template: ../jobs/tlevels-publish-dacpac-job.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      
      - template: ../jobs/tlevels-generate-configs-job.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}

      - template: ../jobs/tlevels-integrationtest-job.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
          dependencies:
            - DeploySQLDatabase
            - DeployInfrastructure
            
      - template: ../jobs/tlevels-publish-site-job.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
          appName: 'uiAppName'
          name: 'Website'
          dependencies:
            - DeployInfrastructure
            - GenerateConfigs
          package: 'Sfa.Tl.ResultsAndCertification.Web.zip'

      - template: ../jobs/tlevels-publish-site-job.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
          appName: 'internalApiAppName'
          name: 'internalAPI'
          dependencies:
            - Publish_Website
            - DeployInfrastructure
            - GenerateConfigs
          package: 'Sfa.Tl.ResultsAndCertification.InternalApi.zip'


      - template: ../jobs/tlevels-publish-function-job.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
          dependencies:
            - DeployInfrastructure
            - GenerateConfigs
            - Publish_internalAPI
          package:  'Sfa.Tl.ResultsAndCertification.Functions.zip'
