resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include: 
    - master   
    - feature/*
    # - feature/lrs-integration
     
pr: none

pool:
  name: 'Azure Pipelines'
  vmImage: 'vs2017-win2016'
  
variables:
  applicationName: resac
stages:
  - template: ./yaml/stages/tlevels-master-stage.yml
