parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
jobs:
- job: DeploySQLDatabase
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  dependsOn:
    - DeployInfrastructure 

  variables:
    SharedResourceGroup: $[stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.SharedVariables.SharedResourceGroup']]
    SharedSQLServerName: $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.sharedSQLServerName'] ]
    DatabaseName: $[ dependencies.DeployInfrastructure.outputs['armOutputs.armOutput.sqlDatabaseName'] ]
    IntTestDatabaseName: $[ dependencies.DeployInfrastructure.outputs['armOutputs.armOutput.IntTestSQLDatabaseName'] ]
  steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'sqldrop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureCLI@2
      displayName: Create temporary SQL firewall rule to allow Azure service connections
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az sql server firewall-rule create -g $(SharedResourceGroup) -s $(SharedSQLServerName) -n "allowAllAzure" --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0'

    - task: SqlAzureDacpacDeployment@1
      displayName: 'Azure SQL Publish'
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        ServerName: '$(SharedSQLServerName).database.windows.net'
        DatabaseName: '$(DatabaseName)'
        SqlUsername: '$(SQLServerAdminUsername)'
        SqlPassword: '$(SQLServerAdminPassword)'
        DacpacFile: '$(System.ArtifactsDirectory)/sqldrop/src/Sfa.Tl.ResultsAndCertification.Database/bin/Release/Sfa.Tl.ResultsAndCertification.Database.dacpac'
        AdditionalArguments: '/p:GenerateSmartDefaults=True /v:environment=$(sqlPublishEnvironmentName)'

    - task: AzureCLI@2
      displayName: Remove temporary SQL firewall rule to allow Azure service connections
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az sql server firewall-rule delete -g $(SharedResourceGroup) -s $(SharedSQLServerName) -n "allowAllAzure"'

    - pwsh: | 
        $SqlConnectionString = "Server=tcp:$(SharedSQLServerName).database.windows.net,1433;Database=$(DatabaseName);User ID=$(ResacSQLServiceAccountUsername);Password=$(ResacSQLServiceAccountPassword);Trusted_Connection=False;Pooling=True;Connect Timeout=30;MultipleActiveResultSets=True"
        Write-Host "##vso[task.setvariable variable=SqlConnectionString;isOutput=true]$SqlConnectionString"        
      name: SqlVariables

    - pwsh: | 
        $IntTestSqlConnectionString = "Server=tcp:$(SharedSQLServerName).database.windows.net,1433;Database=$(IntTestDatabaseName);User ID=$(ResacSQLServiceAccountUsername);Password=$(ResacSQLServiceAccountPassword);Trusted_Connection=False;Pooling=True;Connect Timeout=30;MultipleActiveResultSets=True"
        Write-Host "##vso[task.setvariable variable=IntTestSqlConnectionString;isOutput=true]$IntTestSqlConnectionString"        
      name: IntTestSqlVariables