parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
  - name: dependencies
    type: object
  - name: package
    type: string
jobs:
- job: PublishFunction
  variables:
    functionAppName: $[ dependencies.DeployInfrastructure.outputs['armOutputs.armOutput.functionAppName'] ]

  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  dependsOn:
    - "${{ each dependency in parameters.dependencies }}":
        - "${{dependency}}"  
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'appdrop'
      downloadPath: '$(System.ArtifactsDirectory)'
  
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      appType: 'functionApp'
      appName: '$(functionAppName)'
      package: '$(System.ArtifactsDirectory)/appdrop/${{ parameters.package }}'
      deploymentMethod: 'auto'