name: CreateGrafana
resources:  
  repositories:
    - repository: self
      persistCredentials: true
      clean: true  
    - repository: deployment
      type: github
      endpoint: s126GitHub
      name: s126GitHub/operations-devops-deployment

    - repository: devopsTemplates
      type: github
      endpoint: s126GitHub
      name: s126GitHub/operations-devops-templates
    
trigger:
  branches:
    include:
    - GrafanaPipeline
stages:
  - template: ./grafana/grafana-build.yml@devopsTemplates
    parameters:
      applicationId: $(applicationId)
      purpose: $(purpose)
      environment: $(environment)
      SourcePath: $(System.DefaultWorkingDirectory)/Grafana

