name: CreateGrafana
resources:  
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: deployment
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-deployment

    - repository: devopsTemplates
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

    - repository: devopsTools
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-tools
    
trigger:
  branches:
    include:
    - GrafanaPipeline
variables:
  - name: applicationName
    value: 'resac'
  - group: platform-global-resac
  - group: platform-grafana-resac


stages:
######################## DEV ##############################################
- template: ./Application/grafana-build.yml@devopsTemplates
  parameters:
    serviceId: 's126'
    environmentId: 'd01'
    applicationName: $(applicationName)
    SourcePath: $(System.DefaultWorkingDirectory)\tl-results-and-certification\Grafana\Files
    ServiceConnection: $(devServiceConnection)
    environmentTagName: dev
    subsriptionId: 06569d7b-7c7c-4a46-8c95-a3f30c010d39
######################## TEST ##############################################
- template: ./Application/grafana-build.yml@devopsTemplates
  parameters:
    serviceId: 's126'
    environmentId: 't01'
    applicationName: $(applicationName)
    SourcePath: $(System.DefaultWorkingDirectory)\tl-results-and-certification\Grafana\Files
    ServiceConnection: $(testServiceConnection)
    environmentTagName: test
    dependencies:
      - DeployGrafana_d01
    subsriptionId: 1912dd0c-7966-4e52-ae94-0c77f1e7388d
  