name: CreateGrafana
resources:  
  repositories:
    - repository: self
      persistCredentials: true
      clean: true  
    - repository: deployment
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-deployment

    - repository: devopsTemplates
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
    
trigger:
  branches:
    include:
    - GrafanaPipeline
stages:
- stage: ShowFiles
  jobs: 
  - job: ShowFiles
    steps:
    - checkout: self
    - checkout: deployment
    - checkout: devopsTemplates
    - pwsh: Get-ChildItem -Recurse


  # - template: ./grafana/grafana-build.yml@devopsTemplates
  #   parameters:
  #     applicationId: $(applicationId)
  #     purpose: $(purpose)
  #     environment: $(environment)
  #     SourcePath: $(System.DefaultWorkingDirectory)/Grafana

