name: CreateGrafana
resources:  
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: deployment
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-deployment

    - repository: devopsTemplates
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

    - repository: devopsTools
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-tools
    
trigger:
  branches:
    include:
    - GrafanaPipeline
variables:
  - group: platform-grafana-resac

stages:
- template: ./Application/grafana-build.yml@devopsTemplates
  parameters:
    applicationId: $(applicationId)
    purpose: $(purpose)
    environment: $(environment)
    SourcePath: $(System.DefaultWorkingDirectory)\tl-results-and-certification\Grafana\Files
    ServiceConnection: $(ServiceConnection)

