resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include: 
    - master   
    - feature/*
    # - feature/lrs-integration
     
pr: 
  - feature/* 
  - master
  - develop

pool:
  name: 'Azure Pipelines'
  vmImage: 'windows-latest' #'vs2017-win2016'
  
variables:
  applicationName: resac
stages:
  - template: ./yaml/stages/tlevels-master-stage.yml
    parameters:
      devEnvId: ${{parameters.devEnvId}}
